### ISSUE TITLE
Wasabi falling notes looks garbled on Mesa provided AMD Driver

### ISSUE THREAD

**Issue by bpanca05** [arduano/wasabi#47]
https://github.com/arduano/wasabi/assets/53902591/99c35a6a-9bfe-4c31-8d6b-cdfbecd662e6

This issue happend both on X11 and Wayland session. This is happen because I think there's something wrong with Open Source AMD Driver by Mesa and the Wasabi it self.
Also, if you guys need some logs I can provide but I don't know how to debug.

Here my laptop HW & SW specification:
Hardware:
```
- GPU : AMD Radeon Vega 3 (iGPU)
- CPU : AMD Athlon Silver 3050U
- RAM : 4GB
```

Software
```
- OS : openSUSE Tumbleweed 20231119  
- DE : KDE Plasma 5.25.9
- Kernel vers : 6.6.1
- Qt vers : 5.15.11
- Mesa vers : 23.2.1
```

**Comment by arduano** [comment]
I've seen similar bugs around, I believe it is caused by a bug in integer interpolation on the driver or the hardware. I'm not sure how to fix it, because in theory it should all be correct, but I also have no way to test this bug as I don't have old AMD hardware.

**Comment by ar-cyber** [comment]
Have you installed the proper amdgpu drivers? I have a laptop with old AMD hardware, and it seemed it ran fine in a vm with my graphics card bridged.

**Comment by bpanca05** [comment]
> I've seen similar bugs around, I believe it is caused by a bug in integer interpolation on the driver or the hardware. I'm not sure how to fix it, because in theory it should all be correct, but I also have no way to test this bug as I don't have old AMD hardware.

Well, when I test with Open Source AMDVLK driver (provided by AMD developer), the issue not there anymore. I suspected there's an issue between Open Source AMD Driver by Mesa and the Wasabi it self.

**Comment by arduano** [comment]
Closing because this was likely a driver issue. I don't think I can update the shaders to make this work properly.

**Comment by fucksophie** [comment]
This is still reproducable.

**Comment by bpanca05** [comment]
https://github.com/user-attachments/assets/07a0bbed-c6e4-484d-a204-324132bdeb2e

Update 2026:
This issue clearly a RADV Vulkan driver bug as @arduano mentioned before. With updated RADV from Mesa 26.1.6, Linux kernel 7.1.5, and recompiling the whole Wasabi binary with up-to-date system, still same system as writing this bug report, the issue no longer exist.
