### ISSUE TITLE
KDMAPI Problem

### ISSUE THREAD

**Issue by ar-cyber** [arduano/wasabi#48]
KDMAPI is erroring out when I select it. I ran it in cmd and I have the traceback:

Just to tell you that me windows username is not "runneradmin", so that might be the problem

Using device: NVIDIA GeForce RTX 3050 Ti Laptop GPU (type: DiscreteGpu)
Output device: Headphone (Realtek(R) Audio)
thread 'main' panicked at C:\Users\runneradmin\.cargo\git\checkouts\kdmapi-8825d26b524f8732\9329cfc\src\lib.rs:47:49:
called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src\renderer\swapchain.rs:218:13:
SwapchainFrame not presented.
stack backtrace:
   0:     0x7ff7342455a2 - <unknown>
   1:     0x7ff73406c7ed - <unknown>
   2:     0x7ff73422b341 - <unknown>
   3:     0x7ff7342472da - <unknown>
   4:     0x7ff734246ba9 - <unknown>
   5:     0x7ff7342479eb - <unknown>
   6:     0x7ff7342474bb - <unknown>
   7:     0x7ff734247439 - <unknown>
   8:     0x7ff734247424 - <unknown>
   9:     0x7ff734498d67 - <unknown>
  10:     0x7ff733f01bb6 - <unknown>
  11:     0x7ffb6cf71030 - <unknown>
  12:     0x7ffb6cf74ede - is_exception_typeof
  13:     0x7ffb6cf7f3d0 - _C_specific_handler
  14:     0x7ffb6cf7414c - is_exception_typeof
  15:     0x7ffb6cf7fd11 - _CxxFrameHandler3
  16:     0x7ffb9bbf449f - _chkstk
  17:     0x7ffb9bb6fd54 - RtlUnwindEx
  18:     0x7ffb6cf7f89e - _C_specific_handler
  19:     0x7ffb6cf72e05 - is_exception_typeof
  20:     0x7ffb6cf73224 - is_exception_typeof
  21:     0x7ffb6cf74248 - is_exception_typeof
  22:     0x7ffb6cf7fd11 - _CxxFrameHandler3
  23:     0x7ffb9bbf441f - _chkstk
  24:     0x7ffb9bb6e466 - RtlFindCharInUnicodeString
  25:     0x7ffb9bba4475 - RtlRaiseException
  26:     0x7ffb98fc565c - RaiseException
  27:     0x7ffb6cf766c0 - CxxThrowException
  28:     0x7ff7341b1fcd - <unknown>
  29:     0x7ff734238739 - <unknown>
  30:     0x7ff7342476a1 - <unknown>
  31:     0x7ff7342474f5 - <unknown>
  32:     0x7ff734247439 - <unknown>
  33:     0x7ff734247424 - <unknown>
  34:     0x7ff734498d67 - <unknown>
  35:     0x7ff734499313 - <unknown>
  36:     0x7ff7341a30e6 - <unknown>
  37:     0x7ff7344af563 - <unknown>
  38:     0x7ff7341a35b5 - <unknown>
  39:     0x7ff7344af563 - <unknown>
  40:     0x7ff733f7ff8b - <unknown>
  41:     0x7ff733f810e3 - <unknown>
  42:     0x7ff733ea1e5e - <unknown>
  43:     0x7ff733e991e4 - <unknown>
  44:     0x7ff733edf9b9 - <unknown>
  45:     0x7ff733ee0930 - <unknown>
  46:     0x7ff733ea08f1 - <unknown>
  47:     0x7ff733eda284 - <unknown>
  48:     0x7ff733ede51f - <unknown>
  49:     0x7ff733ee0144 - <unknown>
  50:     0x7ff733edcf05 - <unknown>
  51:     0x7ff733fd93d1 - <unknown>
  52:     0x7ff733efcc18 - <unknown>
  53:     0x7ff733f0df7d - <unknown>
  54:     0x7ff733f0da70 - <unknown>
  55:     0x7ff733f08157 - <unknown>
  56:     0x7ff733f0324e - <unknown>
  57:     0x7ffb9b7a8241 - DispatchMessageW
  58:     0x7ffb9b7a7a8b - CallWindowProcW
  59:     0x7ffad7f61d74 - wglSwapBuffers
  60:     0x7ffb9b7a8241 - DispatchMessageW
  61:     0x7ffb9b7a7efc - DispatchMessageW
  62:     0x7ffb9b7b302d - GetClassLongW
  63:     0x7ffb9bbf33b4 - KiUserCallbackDispatcher
  64:     0x7ffb98e91ad4 - NtUserDispatchMessage
  65:     0x7ffb9b7a7de4 - DispatchMessageW
  66:     0x7ff733f02bb4 - <unknown>
  67:     0x7ff733f0b8ed - <unknown>
  68:     0x7ffb9b7a8241 - DispatchMessageW
  69:     0x7ffb9b7a7efc - DispatchMessageW
  70:     0x7ffb9b7b302d - GetClassLongW
  71:     0x7ffb9bbf33b4 - KiUserCallbackDispatcher
  72:     0x7ffb98e91ad4 - NtUserDispatchMessage
  73:     0x7ffb9b7a7de4 - DispatchMessageW
  74:     0x7ff733f02727 - <unknown>
  75:     0x7ff733fd708f - <unknown>
  76:     0x7ff733e7e796 - <unknown>
  77:     0x7ff733e8f846 - <unknown>
  78:     0x7ff7344884bc - <unknown>
  79:     0x7ffb9a53257d - BaseThreadInitThunk
  80:     0x7ffb9bbaaa58 - RtlUserThreadStart

Hopefully you can fix this so I can move on from Kiva.

**Comment by arduano** [comment]
> The specified module could not be found.
This must be a problem in https://github.com/arduano/kdmapi

Would you be open to helping test this? I can't use kdmapi anymore as I'm now on Linux, and I only work on xsynth. It could be as simple as the path being wrong, maybe something to do with a newer version of OmniMIDI that my kdmapi repository isn't compatible with.

**Comment by arduano** [comment]
More specifically, it's this function:
```rs
fn load_kdmapi_lib() -> Library {
    unsafe { Library::new("OmniMIDI\\OmniMIDI").unwrap() }
}
```

**Comment by arduano** [comment]
Actually, I'll just update it to try both `"OmniMIDI\\OmniMIDI"` and `"OmniMIDI"` and pick the one that works. I'll have it updated soon

**Comment by arduano** [comment]
Anyway, check https://github.com/arduano/wasabi/releases/tag/v0.1.3

If that doesn't work, feel free to re-open the issue, though I won't be able to help with it (you may have to debug it yourself)

**Comment by ar-cyber** [comment]
Nope, the same issue arises. 
Using device: NVIDIA GeForce RTX 3050 Ti Laptop GPU (type: DiscreteGpu)
Output device: Headphone (Realtek(R) Audio)
thread 'main' panicked at C:\Users\runneradmin\.cargo\git\checkouts\kdmapi-8825d26b524f8732\4116b00\src\lib.rs:63:9:
Failed to load KDMAPI library: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }, LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src\renderer\swapchain.rs:218:13:
SwapchainFrame not presented.
stack backtrace:
   0:     0x7ff7e0e93cca - <unknown>
   1:     0x7ff7e0c8e0ad - <unknown>
   2:     0x7ff7e0e7a721 - <unknown>
   3:     0x7ff7e0e95c1a - <unknown>
   4:     0x7ff7e0e954e9 - <unknown>
   5:     0x7ff7e0e9632b - <unknown>
   6:     0x7ff7e0e95dfb - <unknown>
   7:     0x7ff7e0e95d79 - <unknown>
   8:     0x7ff7e0e95d64 - <unknown>
   9:     0x7ff7e10d14e7 - <unknown>
  10:     0x7ff7e0b0a686 - <unknown>
  11:     0x7ffb6cf71030 - <unknown>
  12:     0x7ffb6cf74ede - is_exception_typeof
  13:     0x7ffb6cf7f3d0 - _C_specific_handler
  14:     0x7ffb6cf7414c - is_exception_typeof
  15:     0x7ffb6cf7fd11 - _CxxFrameHandler3
  16:     0x7ffb9bbf449f - _chkstk
  17:     0x7ffb9bb6fd54 - RtlUnwindEx
  18:     0x7ffb6cf7f89e - _C_specific_handler
  19:     0x7ffb6cf72e05 - is_exception_typeof
  20:     0x7ffb6cf73224 - is_exception_typeof
  21:     0x7ffb6cf74248 - is_exception_typeof
  22:     0x7ffb6cf7fd11 - _CxxFrameHandler3
  23:     0x7ffb9bbf441f - _chkstk
  24:     0x7ffb9bb6e466 - RtlFindCharInUnicodeString
  25:     0x7ffb9bba4475 - RtlRaiseException
  26:     0x7ffb98fc565c - RaiseException
  27:     0x7ffb6cf766c0 - CxxThrowException
  28:     0x7ff7e0dc206d - <unknown>
  29:     0x7ff7e0e86f19 - <unknown>
  30:     0x7ff7e0e95fe1 - <unknown>
  31:     0x7ff7e0e95e35 - <unknown>
  32:     0x7ff7e0e95d79 - <unknown>
  33:     0x7ff7e0e95d64 - <unknown>
  34:     0x7ff7e10d14e7 - <unknown>
  35:     0x7ff7e0db3f92 - <unknown>
  36:     0x7ff7e10ef7c3 - <unknown>
  37:     0x7ff7e0db5125 - <unknown>
  38:     0x7ff7e10ef7c3 - <unknown>
  39:     0x7ff7e0b97c76 - <unknown>
  40:     0x7ff7e0b996cb - <unknown>
  41:     0x7ff7e0aa640e - <unknown>
  42:     0x7ff7e0aa8324 - <unknown>
  43:     0x7ff7e0ae8e99 - <unknown>
  44:     0x7ff7e0ae9e10 - <unknown>
  45:     0x7ff7e0a93721 - <unknown>
  46:     0x7ff7e0adab6c - <unknown>
  47:     0x7ff7e0ae6812 - <unknown>
  48:     0x7ff7e0ae9624 - <unknown>
  49:     0x7ff7e0ae2252 - <unknown>
  50:     0x7ff7e0bf1318 - <unknown>
  51:     0x7ff7e0b056e2 - <unknown>
  52:     0x7ff7e0b16a6d - <unknown>
  53:     0x7ff7e0b16560 - <unknown>
  54:     0x7ff7e0b10c47 - <unknown>
  55:     0x7ff7e0b0bd4e - <unknown>
  56:     0x7ffb9b7a8241 - DispatchMessageW
  57:     0x7ffb9b7a7a8b - CallWindowProcW
  58:     0x7ffad7f61d74 - wglSwapBuffers
  59:     0x7ffb9b7a8241 - DispatchMessageW
  60:     0x7ffb9b7a7efc - DispatchMessageW
  61:     0x7ffb9b7b302d - GetClassLongW
  62:     0x7ffb9bbf33b4 - KiUserCallbackDispatcher
  63:     0x7ffb98e91ad4 - NtUserDispatchMessage
  64:     0x7ffb9b7a7de4 - DispatchMessageW
  65:     0x7ff7e0b0b68c - <unknown>
  66:     0x7ff7e0b143dd - <unknown>
  67:     0x7ffb9b7a8241 - DispatchMessageW
  68:     0x7ffb9b7a7efc - DispatchMessageW
  69:     0x7ffb9b7b302d - GetClassLongW
  70:     0x7ffb9bbf33b4 - KiUserCallbackDispatcher
  71:     0x7ffb98e91ad4 - NtUserDispatchMessage
  72:     0x7ffb9b7a7de4 - DispatchMessageW
  73:     0x7ff7e0b0b1f7 - <unknown>
  74:     0x7ff7e0beefba - <unknown>
  75:     0x7ff7e0a82a76 - <unknown>
  76:     0x7ff7e0a83296 - <unknown>
  77:     0x7ff7e10bcbbc - <unknown>
  78:     0x7ffb9a53257d - BaseThreadInitThunk
  79:     0x7ffb9bbaaa58 - RtlUserThreadStart

It may be because the user Specified is "runneradmin", but that may be rust.

**Comment by ar-cyber** [comment]
Actually, it might be my machine...

**Comment by arduano** [comment]
I'm not sure what it could be

**Comment by ar-cyber** [comment]
It looks like any machine I run it on doesn't work,
